#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01). Let’s also add other subdomains to make our life easier, and write a Bash script that will display information about subdomains.

if [ “$# = 1 ]
then 
	mydomains=(“www” “Ib-01” “web-01” “web-02”)
	for sub_domain in “${mydomains[@]}”
	do
		record_type = $(dig $sub_domain.$1 | grep -A1 ‘ANSWER SECTION’ | tall -1 | awk '{print $4}')
		destination=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
		echo "The subdomain $2 is a $record_type record and points to $destination"1
done
fi
